#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running pre-commit hooks..."

echo "Running tests..."
bun test || exit 1

echo "Running linter..."
bun run lint || exit 1

echo "Running formatter..."
bun run format || exit 1

echo "Running type check..."
bun run check-types || exit 1

echo "All checks passed!"
